"""
Version and identity information for the application.
Format: {app_name}/{version}@{git_hash}
Example: beaverhabits/1.0.0@8f1325a

NOTE: This file will be overwritten by GitHub Actions during release.
DO NOT EDIT THIS FILE MANUALLY.
"""

IDENTITY = ""  # Will be set to git commit hash (e.g. "beaverhabits/1.0.0@8f1325a")
